In [19]:
#Q1
#홍길동 씨의 과목별 점수는 다음과 같다. 홍길동 씨의 평균 점수를 구해 보자.

#과목	점수
#국어	80
#영어	75
#수학	55
ko = 80
English = 75
Math = 55
name = "Hong's"
avgPoints = (ko+English+Math)/3

TypeError: ignored